version: '3.0'
services:
  rasa-train:
    network_mode: host
    image: rasa/rasa:2.6.3-full
    user: root
    volumes:
      - ./:/app
    command:
      - train
  rasa-run:
    network_mode: host
    image: rasa/rasa:2.6.3-full
    user: root
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action-server:
    network_mode: host
    image: 71d4daa7a6d2
    ports:
      - 5055:5055